// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Counter struct {
	Key       string    `json:"key"`
	Value     int64     `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Url struct {
	ID          int64         `json:"id"`
	ShortCode   string        `json:"short_code"`
	OriginalUrl string        `json:"original_url"`
	CreatedAt   time.Time     `json:"created_at"`
	LastUsedAt  sql.NullTime  `json:"last_used_at"`
	UsageCount  sql.NullInt64 `json:"usage_count"`
}
