// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteURL(ctx context.Context, shortCode string) error
	GetAllURLs(ctx context.Context) ([]Url, error)
	GetCounter(ctx context.Context, key string) (int64, error)
	GetURL(ctx context.Context, shortCode string) (Url, error)
	IncrementCounter(ctx context.Context, arg IncrementCounterParams) (int64, error)
	SetCounter(ctx context.Context, arg SetCounterParams) error
	URLExists(ctx context.Context, shortCode string) (int64, error)
	UpdateUsage(ctx context.Context, arg UpdateUsageParams) error
}

var _ Querier = (*Queries)(nil)
